name: Test Jenkins Action

on:
  push:


jobs:

  testaction:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - id: testjenkinsaction
        uses: appleboy/jenkins-action@master
        with:
         url: "http://services-uscentral.skytap.com:14539"
         user: "asanchez"
         token: 115bbb7078b572878f748eb99c04864355
         job: "GithubtestUFT"

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://mfjr.atlassian.net
          JIRA_USER_EMAIL: armando.sanchez@microfocus.com
          JIRA_API_TOKEN: 0gF6b6ErI1A72XLTM1Ix9D5B
          
      - id: create
        uses:  atlassian/gajira-create@master
        with:
          project: ALMOctane
          issuetype: Build
          summary: |
            Build completed for ${{ github.repository }}
          description: |
            Compare branch
          fields: '{"customfield_10171": "test"}'
        
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
