name: Test Jenkins Action

on:
  workflow_dispatch:


jobs:

  testaction:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - id: testjenkinsaction
        uses: jabbukka/jenkins-trigger@main
        with:
           url: http://services-uscentral.skytap.com:14539
           job_name: GithubtestUFT
           user_name: asanchez
           api_token: 115bbb7078b572878f748eb99c04864355
           wait: "true"
           timeout: "1000"
